CREATE TABLE CUSTOMERS(
    ID int NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary Key',
    DISCORD_ID UNIQUE,
    DISCORD_NAME VARCHAR(255),
    JOIN_TIME DATETIME,
    UPDATE_TIME DATETIME,
    NOTES VARCHAR(255),
) DEFAULT CHARSET UTF8 COMMENT '';